name: Deploy
on:
  push:
    branches:
      - master
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Install global dependencies
        run: sudo npm install -g firebase-tools
      - name: Deploy to Firebase development
        if: github.ref == 'refs/heads/develop'
        run: |
          printenv GOOGLE_JSON > creds.json
          firebase deploy -P dev --non-interactive
        env:
          GOOGLE_JSON: ${{ secrets.FIREBASE_DEV_2_JSON }}
          GOOGLE_APPLICATION_CREDENTIALS: creds.json
          SKYAPP_SECRET_KEY: ${{ secrets.SKYAPP_SECRET_KEY }}
          CHATBOT_URL: https://e-rouska-custom-ui-test.eu-de.mybluemix.net/chatWindow.js
      - name: Deploy to Firebase production
        if: github.ref == 'refs/heads/master'
        run: |
          printenv GOOGLE_JSON > creds.json
          firebase deploy -P prod --non-interactive
        env:
          GOOGLE_JSON: ${{ secrets.FIREBASE_PROD_JSON }}
          GOOGLE_APPLICATION_CREDENTIALS: creds.json
          SKYAPP_SECRET_KEY: ${{ secrets.SKYAPP_SECRET_KEY }}
          CHATBOT_URL: https://e-rouska-custom-ui.eu-de.mybluemix.net/chatWindow.js
